### ISSUE TITLE
Course-overview page: Create new courses 

### ISSUE THREAD

**Issue by ImkeMey** [leaonline/leaonline-teacher#17]
**Summarize the feature from a user perspective in one or two sentences**
The User can create new courses und and invite participants. 

**Included and excluded behavior**
When the user clicks on the "Add new class"-Button, a model with a form should open. 
There the user can fill in the name of the course, the starting and ending date and invite participants.

The user should be able to save or cancel this process. 

It must not...

- [ ] have the labels directly written but uses the translation ids

**Optional: Add a detailed description, if the requirement is more complex**

#### Button "Add new class" ("Neuen Kurs anlegen")
- Label: "pages.myClasses.addNew"
- Color: #F59D1D 
- Font: Semikolon Plus Bold 

#### Button "Cancel" ("Abbrechen")
- Label: "actions.cancel"
- Color: #193B5E
- Font: Semikolon Plus Bold 

#### Form
- Typo Color: #646464 
- Font: Semikolon Plus Bold and Regular 

**Optional: Additional images or sketches, flowcharts etc.**
![02-kursuebersicht-kurs-anlegen](https://user-images.githubusercontent.com/62182064/78543269-b75ad700-77f8-11ea-948b-3467cbcaceaf.png)
![03-kursuebersicht-kurs-anlegen](https://user-images.githubusercontent.com/62182064/78543277-ba55c780-77f8-11ea-84e5-21ab3095916a.png)

**Comment by ImkeMey** [comment]
@jankapunkt I'm not sure what to write in "it must not..." This issue seams so clear to me. Can you give me an example what to write there? Or is it ok to leave it blank?

**Comment by jankapunkt** [comment]
@ImkeMey I updated your initial task but I am still unsure why we would use the `Semikolon` font for the teachers? As a non illiterate this font annoys me a lot when reading it. I could imagine it for headlines but for all text?

**Comment by ImkeMey** [comment]
@jankapunkt thanks. Well, I don't think Semikolon is super annoying. But we can discuss this. It might be good for consistency to also use Semikolon in the Dashboard. Or we could test the font in the upcoming usability tests. @kadewe what do you think?

**Comment by jankapunkt** [comment]
implemented in #31
