### ISSUE TITLE
Course-overview page: list courses 

### ISSUE THREAD

**Issue by ImkeMey** [leaonline/leaonline-teacher#18]
**Summarize the feature from a user perspective in one or two sentences**
The user sees three lists of his courses, segmented in

- running ("Laufend") 
  - has a `startedAt` but no `completedAt` field
  - label is "pages.myClasses.running"
- upcoming ("Ausstehend") 
  - has neither `startedAt` nor a `completedAt` field
  - label is "pages.myClasses.upcoming"
- completed ("Abgeschlossen")
  - has a `startedAt` and a `completedAt` field
  - label is "pages.myClasses.completed"

**Included and excluded behavior**

- It should show three different lists with the courses the user created. The first list is "running", then "upcoming" and "completed".
- Inside these lists the **courses should be sorted by name**. 
- Each list element shout show the name of the course.  

It **must not** show the participants of each course or the starting and ending dates. 

**Optional: Add a detailed description, if the requirement is more complex**

- Background Color: #F3F3F3 

- Lists
Background: #FFFFFF 
Font: Semikolon Plus Bold 
Font Color: #193B5E 

**Optional: Additional images or sketches, flowcharts etc.**
![01-kursuebersicht](https://user-images.githubusercontent.com/62182064/78543193-985c4500-77f8-11ea-8117-2e057444f90f.png)

**Comment by ImkeMey** [comment]
@jankapunkt What should we do with the drafts? Can/Should I upload each draft to each issue? I sent everything to Tushar - Do you think I should also upload it here?

**Comment by ImkeMey** [comment]
@jankapunkt do you have sth to add?

**Comment by jankapunkt** [comment]
@ImkeMey I updated the task with English terms (we will have our translation in a separate file)

**Comment by ImkeMey** [comment]
@jankapunkt thanks. I'll keep that in mind.
