### ISSUE TITLE
Course-overview page: Delete courses 

### ISSUE THREAD

**Issue by ImkeMey** [leaonline/leaonline-teacher#19]
**Summarize the feature from a user perspective in one or two sentences**
By clicking on the delete button (button with trash icon) the user can delete a course. 

**Included and excluded behavior**

It should open a modal, in which the is asked to confirm the process. If the users confirms, the course should be deleted. 

It must not delete the course without confirmation by the user. 

**Optional: Add a detailed description, if the requirement is more complex**

- Delete Button
Color: #D95A7D 
Icon: https://fontawesome.com/icons/trash?style=solid 

**Optional: Additional images or sketches, flowcharts etc.**

![01-kursuebersicht](https://user-images.githubusercontent.com/62182064/78543610-2f290180-77f9-11ea-8b5e-ec4a64256459.png)

**Comment by ImkeMey** [comment]
@jankapunkt Do you have sth to add?

**Comment by jankapunkt** [comment]
lgtm

**Comment by jankapunkt** [comment]
implemented in #31
