### ISSUE TITLE
Course-overview page: edit courses

### ISSUE THREAD

**Issue by ImkeMey** [leaonline/leaonline-teacher#20]
**Summarize the feature from a user perspective in one or two sentences**
The User can edit existing courses.

**Included and excluded behavior**
When the user clicks on the edit-Button (pen icon), a model with a form should open.
There the user can edit the name of the course, the starting and ending date and add or erase participants.
The user should be able to save or cancel this process.

It must not...

**Optional: Add a detailed description, if the requirement is more complex**

- Edit Button:
Color: #35CB91
Icon: https://fontawesome.com/icons/pen?style=solid 

- Cancel Button (Modal) 
Color: #193B5E
Font: Semikolon Plus Bold 

- Save Button (Modal)
Color: #35CB91 
Font: Semikolon Plus Bold 

- Modal
Font: Semikolon Plus Bold and Regular 
Font Color: #646464 
Background Color: #FFFFFF 

**Optional: Additional images or sketches, flowcharts etc.**
![04-kursuebersicht-kurs-bearbeiten](https://user-images.githubusercontent.com/62182064/78544807-0144bc80-77fb-11ea-9210-5dd5910a4513.png)

**Comment by ImkeMey** [comment]
@jankapunkt Do you have sth to add?

**Comment by jankapunkt** [comment]
lgtm

**Comment by jankapunkt** [comment]
implemented in #31
