### ISSUE TITLE
Course-overview page: show/get to a course

### ISSUE THREAD

**Issue by ImkeMey** [leaonline/leaonline-teacher#21]
**Summarize the feature from a user perspective in one or two sentences**
The user can click on a button and is redirected to the "course page". 

**Included and excluded behavior**
When the user clicks on the "show course"-button (eye icon) he/she should be redirected to the course view of the selected course. 

It must not...

- [ ]

**Optional: Add a detailed description, if the requirement is more complex**

- Link Button
Color: #193B5E 
Icon: https://fontawesome.com/icons/eye?style=solid 

**Optional: Additional images or sketches, flowcharts etc.**
![Web 1920 – 29](https://user-images.githubusercontent.com/62182064/78566086-09aeee80-781f-11ea-8cb3-7d4e9a248130.png)

**Comment by ImkeMey** [comment]
@jankapunkt Do you have sth to add?

**Comment by jankapunkt** [comment]
lgtm
